config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :questions

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 3 }

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  def show
    @question = Question.find_by id: params[:id]
  end

  def destroy
    @question = Question.find_by id: params[:id]
    @question.destroy
    redirect_to questions_path
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]
    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>MyMagaz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to 'Домой', root_path %></li>
      <li><%= link_to 'Questions', questions_path %></li>
    </ul>
  </nav>
  <main>
  <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Наш магазин</h1>

<p>Добро пожаловать</p>

<footer>
  &copy; RS8 <%= Time.now.year %>
</footer>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, minlength: 3, placeholder: "Title" %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, required: true, minlength: 3 %>
  </div>

  <%= f.submit "Отправить вопрос!" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Изменить вопрос</h1>

<%= @question.inspect %>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
<h2><%= question.title %></h2>

<time datetime="<%= question.formatted_created_at %>">
  <%= question.formatted_created_at %>
</time>

<p>
  <%= question.body %>
  <br>
  <%= link_to 'Показать', question_path(question) %> |
  <%= link_to 'Изменить', edit_question_path(question) %> |
  <%= link_to 'Удалить', question_path(question), data: {method: :delete, confirm: 'Вы уверены?'} %>
</p>
<% end %>

app/views/questions/new.html.erb
<h1>Новый вопрос</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p>
  <time datetime="<%= @question.formatted_created_at %>">
    <%= @question.formatted_created_at %>
  </time>
  <br>
  <%= @question.body %>
</p>